### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by IT0825** [IT0825/furima-36548#21]
# URL
https://furima-36548.herokuapp.com/
# Basic認証のIDとパスワード
ID:admin
パスワード:2222
# 出品者用のメールアドレスとパスワード
メールアドレス:test@com
パスワード:Ya0000
# 購入者用のメールアドレスとパスワード
メールアドレス:test2@com
パスワード:Yb0000

**Comment by snkw-works** [comment]
@IT0825 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **商品出品・編集画面にて、発送までの日数は、「---、1\~2日で発送、2\~3日で発送、4\~7日で発送」の4項目が表示されるよう修正しましょう（--- は初期値として設定すること）**
「2\~3日で発送」ではなく「3\~4日で発送」と表示されている状態です。
<img width="375" alt="スクリーンショット 2021-08-17 12 45 47" src="https://user-images.githubusercontent.com/54050089/129660483-f4cbb684-b07d-4a3b-b5df-da58db18edb6.png">

- [ ] **商品編集画面にて、エラーハンドリングができるよう修正しましょう（入力に問題がある状態で「変更する」ボタンが押された場合、情報は保存されず、編集ページに戻りエラーメッセージが表示されること）**
入力に問題がある状態で「変更する」ボタンをクリックすると、エラー画面に遷移してしまい、エラーメッセージが確認できない状態です。
<img width="693" alt="スクリーンショット 2021-08-17 12 49 42" src="https://user-images.githubusercontent.com/54050089/129660737-889f7823-fd69-4211-a310-4dc8c7b6284b.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by IT0825** [comment]
修正完了いたしました。
再度確認をお願いします。

**Comment by takumi0530** [comment]
@IT0825 さん、フリマアプリ達成要件分の開発お疲れ様でした！
ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

**＜今後の学習例＞**
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

**＜提出物＞**
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
**※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。**

**＜最終課題に関する締め切りについての動画＞**
`https://master.tech-camp.in/v2/curriculums/6852`

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/129670576-93edb11f-3b45-46d7-a86a-1253385cde4e.png)
